# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20191023_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hair_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
