# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_product_hair_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
