# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_product_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchases',
        ),
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='first_app.Product'),
        ),
    ]
